version: '3.8'
services:
  nginx:
   image: geoffop96/nginx:latest
    #  build: ./nginx
   links:
     - app:app
     - app2:app2
   ports:
     - "80:80"

  app:
    # build:
    #   context: ./app
    image: geoffop96/website:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000"

  app2:
    # build:
    #   context: ./app
    image: geoffop96/website:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000"

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  redis_data:
